"""empty message

Revision ID: 0423fd91eba9
Revises: 6f912131c21d
Create Date: 2024-05-29 07:07:14.336426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0423fd91eba9'
down_revision = '6f912131c21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_location', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('pickup_location', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('task_delivery_location_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('task_pickup_location_id_fkey', type_='foreignkey')
        batch_op.drop_column('delivery_location_id')
        batch_op.drop_column('pickup_location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_location_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('task_pickup_location_id_fkey', 'address', ['pickup_location_id'], ['id'])
        batch_op.create_foreign_key('task_delivery_location_id_fkey', 'address', ['delivery_location_id'], ['id'])
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('delivery_location')

    # ### end Alembic commands ###
