"""empty message

Revision ID: 4b9c418273d9
Revises: 4b8cda3b2e6b
Create Date: 2024-05-27 16:17:43.372731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9c418273d9'
down_revision = '4b8cda3b2e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=True))
        batch_op.alter_column('seeker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['requester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seeker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###
