"""empty message

Revision ID: 61df98ff7cc0
Revises: 2c18a999422a
Create Date: 2024-05-24 21:46:28.275220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61df98ff7cc0'
down_revision = '2c18a999422a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holi')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=24), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('TASK_SEEKER', 'REQUESTER', 'BOTH', 'NONE', name='roleenum'), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    op.create_table('holi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('TASK_SEEKER', 'REQUESTER', 'BOTH', 'NONE', name='roleenum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='holi_pkey'),
    sa.UniqueConstraint('email', name='holi_email_key'),
    sa.UniqueConstraint('username', name='holi_username_key')
    )
    # ### end Alembic commands ###
