"""empty message

Revision ID: b8426bfa437e
Revises: e602e076a0a5
Create Date: 2024-05-26 05:40:15.695973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8426bfa437e'
down_revision = 'e602e076a0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_open_tasks', sa.Integer(), nullable=True))

    with op.batch_alter_table('task_seeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ongoing_tasks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_seeker', schema=None) as batch_op:
        batch_op.drop_column('total_ongoing_tasks')

    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.drop_column('total_open_tasks')

    # ### end Alembic commands ###
