"""empty message

Revision ID: d42149deea9e
Revises: 0423fd91eba9
Create Date: 2024-05-29 07:40:38.726690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42149deea9e'
down_revision = '0423fd91eba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_location_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pickup_location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'address', ['pickup_location_id'], ['id'])
        batch_op.create_foreign_key(None, 'address', ['delivery_location_id'], ['id'])
        batch_op.drop_column('delivery_location')
        batch_op.drop_column('pickup_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pickup_location_id')
        batch_op.drop_column('delivery_location_id')

    # ### end Alembic commands ###
